version: "3.0"
services:
  backend:
    env_file: .env
    build: .
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 3000:${PORT}
    volumes:
      - /src:/src
    depends_on:
      - db-backend
    networks: 
      - my-network
  db-backend:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=message_dev
    ports:
      - 5432:5432
    volumes:
      - ./data/db:./var/lib/postgresql/data
    networks:
      - my-network
networks:
  my-network:
   driver: bridge
